### PR TITLE
go-perfevents: enable basic support for generic hardware events

### PR DESCRIPTION
**Pull request by hkshaw1990**
Adds an implementation of perfevents API in golang.

### CODE REVIEW

**Comment by bhs** [comment]
@hkshaw1990 thank you for sending this out.

Before I review this in any detail, what's the general game plan as far as actual OT integration is concerned? Apologies if you described this somewhere else, I am juggling too many things. Feel free to send me an "RTFM" message as long as there's a pointer :)

Thanks.

**Comment by hkshaw1990** [comment]
@bensigelman thanks for the suggestion.
I have created an issue to track the immediate plan with respect to OT integration (https://github.com/opentracing-contrib/perfevents/issues/2). The first one in the checklist will be enough to integrate perfevents with OT. It defines the basic API (to create, read and close perfevents) and exposes 7 perf events (wrt cpu), which are good enough to start with. This PR does all that and I have already sent PRs to opentracing-go and zipkin-go-opentracing which leverages these events.

**Comment by bhs** [comment]
I am happy to basically rubberstamp this part of the work since I don't really have any right to review the details :)

If there are problems with the actual programmatic API as the rest of the PRs unfold, we can adjust at that point.

Thanks for doing this.  :thumbsup:

**Comment by hkshaw1990** [comment]
Alright, thanks @bhs. Merging this PR.

**Pull request merged**
